DROP TABLE DVD IF EXISTS;
CREATE TABLE DVD (
  ID int IDENTITY NOT NULL PRIMARY KEY,
  ANNEE int default NULL,
  ZONE int NOT NULL,
  EDITION varchar(255) default NULL
);
DROP TABLE FILM IF EXISTS;
CREATE TABLE FILM (
  ID int IDENTITY NOT NULL PRIMARY KEY,
  ANNEE int NOT NULL,
  TITRE varchar(255) NOT NULL,
  TITRE_O varchar(255) default NULL,
  ID_DVD int NOT NULL,
  RIPPED int DEFAULT NULL,
  POSTER_PATH varchar(255) default NULL,
  TMDB_ID BIGINT default NULL,
  constraint DVD_FK foreign key (ID_DVD) references DVD(ID)
);
DROP TABLE PERSONNE IF EXISTS;
CREATE TABLE PERSONNE (
  ID int IDENTITY NOT NULL PRIMARY KEY,
  NOM varchar(255) NOT NULL,
  PRENOM varchar(255) default NULL,
  DATE_N date default NULL,
  ID_PAYS int default NULL
);
DROP TABLE ACTEUR IF EXISTS;
CREATE TABLE ACTEUR (
  ID IDENTITY NOT NULL PRIMARY KEY,
  ID_PERSONNE int NOT NULL ,
  ID_FILM int NOT NULL,
  constraint ACTEUR_PERSONNE_FK foreign key (ID_PERSONNE) references PERSONNE(ID),
  constraint ACTEUR_FILM_FK foreign key (ID_FILM) references FILM(ID)
  
);
DROP TABLE REALISATEUR IF EXISTS;
CREATE TABLE REALISATEUR (
  ID IDENTITY NOT NULL PRIMARY KEY,
  ID_PERSONNE int NOT NULL ,
  ID_FILM int NOT NULL,
  constraint REALISATEUR_PERSONNE_FK foreign key (ID_PERSONNE) references PERSONNE(ID),
  constraint REALISATEUR_FILM_FK foreign key (ID_FILM) references FILM(ID)
);