DROP TABLE ACTEUR;


CREATE TABLE `ACTEUR` (
  `ID` int(11) NOT NULL auto_increment,
  ID_PERSONNE int(11) NOT NULL ,
  ID_FILM int(11) NOT NULL,
  PRIMARY KEY  (`ID`),
  KEY `FK20ED8438B0040A` (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

DROP TABLE REALISATEUR


CREATE TABLE `REALISATEUR` (
  `ID` int(11) NOT NULL auto_increment,
  ID_PERSONNE int(11) NOT NULL ,
  ID_FILM int(11) NOT NULL,
  PRIMARY KEY  (`ID`),
  KEY `FK20ED8438B0040A` (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
