spring:
  cloud:
    gateway:
      routes:
        - id: dvdtheque-rest-services
          uri: lb://dvdtheque-rest-services
          port: 8083
          predicates:
            - Path=/films/**
          filters:
            - StripPrefix=2