spring:
  cloud:
    gateway:
      routes:
        - id: dvdtheque-rest-services
          uri: http://localhost:8083/
          predicates:
            - Path=/dvdtheque/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - PUT