spring:
  application:
    name: dvdtheque-rest-services
  cloud:
    config:
      fail-fast: true
logging:
  level:
    root: info      
management:
  endpoints:
    web:
      exposure:
        include: "*"
