spring:
  application:
    name: dvdtheque-service
  cloud:
    config:
      fail-fast: true
logging:
  level:
    org:
        springframework:
          cloud:
            openfeign: TRACE
          security:
            web: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"