spring:
  application:
    name: dvdtheque-service
  cloud:
    config:
      fail-fast: true
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    fr.fredos.dvdtheque: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"