package fr.fredos.dvdtheque.common.enums;

public enum JmsStatus {
	CLEAN_DB_INIT,
	CLEAN_DB_COMPLETED,
	IMPORT_INIT, 
	IMPORT_COMPLETED, 
	FILM_PROCESSOR_INIT, 
	FILM_PROCESSOR_COMPLETED,
	FILE_ITEM_READER_INIT,
	FILE_ITEM_READER_COMPLETED,
	FILM_CSV_LINE_MAPPER_INIT,
	FILM_CSV_LINE_MAPPER_COMPLETED,
	FILM_CSV_LINE_TOKENIZER_INIT,
	FILM_CSV_LINE_TOKENIZER_COMPLETED,
	DB_FILM_WRITER_INIT,
	DB_FILM_WRITER_COMPLETED
}
