server:
  port: 2222
spring:
  application:
    name: dvdtheque-resource-server
  profiles:
    active: local
  cloud:
    config:
      uri: http://192.168.1.103:8888
      fail-fast: true
logging:
  level:
    org.springframework.security: TRACE